### ISSUE TITLE
nick change when going afk

### ISSUE THREAD

**Issue by warmwaffles** [ircrelay/suggestions#10]
I'd love it if for some networks I could specify a nick change when I go afk

when I quit my IRC session

`/nick warmwaffles|afk`

when I log in to my IRC session

`/nick warmwaffles`

**Comment by warmwaffles** [comment]
This is something addressed in #6

**Comment by pearkes** [comment]
Hey! Thanks for the suggestion. We currently support the `/away` command, and can automatically set a message (configurable on https://www.ircrelay.com).

We heard from someone else in the community that is the "preferred" method. See #6 :)

**Comment by pearkes** [comment]
Ha, good timing. Yea, I'll leave this open and tag it for November. Can't promise it will get in there (other features are taking priority) but if it fits we'll do it.

Thanks for the suggestion.
