### ISSUE TITLE
Quick add preconfigured IRC servers

### ISSUE THREAD

**Issue by warmwaffles** [ircrelay/suggestions#11]
Something like pre filled values for Freenode, Quakenet, etc... would be nice to get up and running.

**Comment by mitchellh** [comment]
This is a pretty great idea. :+1:

**Comment by pearkes** [comment]
Tagged it for November, not top priority ([super cool stuff](https://github.com/ircrelay/suggestions/issues?milestone=1&state=open) is above it) but totally agree that it would make life smooth.  Thanks :)
