### ISSUE TITLE
Bitlbee and camper_van?

### ISSUE THREAD

**Issue by nicksergeant** [ircrelay/suggestions#16]
This is likely out of scope, but I would pay $5+/month for hosted [bitlbee](http://www.bitlbee.org/main.php/news.r.html) + [camper_van](https://github.com/zerowidth/camper_van) instances that are privatized to my ircrelay account.

Maintaining instances of both bitlbee and camper_van on my personal servers is a PITA, but both are critical for work purposes. I'd gladly pay to have secure instances of these for me to use. I know there are hosted [bitlbee servers](http://www.bitlbee.org/main.php/servers.html), but they're public and obviously trust is an issue. Having isolated processes is important, I think.

**Comment by pearkes** [comment]
Thank you. This is a cool idea (never heard about camper_van either!)

However, I think it introduces too much product and technical complexity for now. We're trying hard to offer a consistent service that does one thing well (hosted bouncer, use your own client) and don't think it's wise to drift from that too much.

Really appreciate you voicing this, and consider it noted. I personally would love this too, if that counts for anything. :)

**Comment by nicksergeant** [comment]
Totally agree! Thanks for hearing me out :)
