### ISSUE TITLE
Send Recent Messages On Connect

### ISSUE THREAD

**Issue by pearkes** [ircrelay/suggestions#2]
In a perfect world, you could send messages since last `foo` message. This would require sending up that message from a client, which only a few clients support.

Another option is to send n last messages on connect. This could be configured either with a message on connect, or in the IRCRelay admin area.

We'll think on this one.

cc/ @skottler

**Comment by grawity** [comment]
Relevant: http://ircv3.org/extensions/server-time-3.2 – a new IRC extension that allows bouncers to send original timestamps of recent messages. Currently supported by Textual, Weechat and ZNC.

**Comment by pearkes** [comment]
@grawity We currently support server-time! If your client supports it (not all do) then you should be seeing the timestamps on the messages replayed from your buffer.

**Comment by grawity** [comment]
@pearkes Ah, that's nice.

(The issue text – "Another option is to send n last messages on connect. This could be configured …" – made me think this was just in the planning stage or such.)

**Comment by pearkes** [comment]
@grawity Ah, gotcha. Yea, that wasn't clear.

To clarify:

The current behavior is to replay the buffer[1] when a client connects. The behavior discussed in this issue suggests for the replay to include both the buffer + the n last messages, so there is more context for each room. People who quit their client / change computers frequently would benefit most from this.

[^1]: The buffer is the messages received by IRCRelay when no client was connected.

**Comment by pearkes** [comment]
This is going to be handled indirectly by #4 which has been tagged for the november milestone.
