### ISSUE TITLE
Multiple Client Playback

### ISSUE THREAD

**Issue by d0ugal** [ircrelay/suggestions#4]
Hi,

Is it possible to have a playback buffer per IRC client? For example, two laptops or mobile devices and a laptop etc.

Or, perhaps a workaround of connecting once to the target IRC server, and then connecting to that instance with two (or more) other instances of irc relay. Then finally connecting to those with the end client?

**Comment by pearkes** [comment]
Whoa. You just blew my mind with the potential of stringing together multiple IRCRelay instances.

```
├── master
    ├── mobile
    ├── laptop
    └── desktop
```

Mobile, desktop and laptop always receive _all_ messages from master. They replay their buffers as they are connected to.

I'm trying to think of any limitations other then one obvious one which blocks it now, which is sending a username for a network, but that we can fix. But, sometimes I get all excited about something and fail to see an obvious flaw.

This is an often requested feature - but it's unfortunately tough to solve with N clients and N messages in a buffer.

IRCRelay Inception just might work. Let me talk to @mitchellh as well.

Amazing.

**Comment by d0ugal** [comment]
Exactly!

It's most certainly a hack but its one I've seen in ZNC before. I just never got around to doing it when I ran my own instance. [They even cover it in the FAQ](http://wiki.znc.in/FAQ#How_to_store_private_messages_even_when_user_is_attached.2C_so_other_clients_can_see_them.3F).

I imagine the formatting could become a little weird - would messages be double timestamped in the playback? Something I could live with :smile:.

**Comment by stabenfeldt** [comment]
That would have been a nice feature! :+1:

**Comment by pearkes** [comment]
Yup! It's under the November sprint milestone.

**Comment by mitchellh** [comment]
Great news! This is now done. There will be an announcement on Twitter soon, but if you log into your account online you will probably be able to figure it out. ;)

It isn't TOTALLY issue-less. We're still working out some minor kinks, but they're minor, and things work great.

**Comment by d0ugal** [comment]
Woohoo! Thanks, I'll take a look tomorrow when I'm back at a real computer.
