### ISSUE TITLE
Enable the AwayNick module

### ISSUE THREAD

**Issue by killtheliterate** [ircrelay/suggestions#6]
I find it incredibly useful to have an away nickname set, due to the way my company uses IRC. Is this possible, or should an away message suffice?

**Comment by indirect** [comment]
I believe this is the rationale for avoiding AwayNick: http://bisqwit.iki.fi/jutut/away.html

**Comment by mitchellh** [comment]
Sorry to have never responded to this! This is actually possible already. You can log into your ircrelay.com console and in your network settings set an away nickname. IRCRelay will automatically set this if there are no clients connected for 5 seconds.

**Comment by mitchellh** [comment]
In fact, I am incorrect. We support away messages rather than away nicks. According to the link by @indirect, this is the most correct approach. I think we'd like to stick with this for now. Thanks!
