### ISSUE TITLE
Looks like a bug in the e-mail/billing?

### ISSUE THREAD

**Issue by d0ugal** [ircrelay/suggestions#9]
This seems a bit cheap...

```
Hello,

This email serves as a receipt for your monthly IRCRelay plan.

Account: [removed]
Plan Type: Basic
Start Date: Fri, 02 Aug 2013 08:22:32
End Date: Mon, 02 Sep 2013 08:22:32
Total Billed: $-1
Thank you for your business! Please reply to this email with any questions.

Best,

The IRCRelay Team
```

**Comment by pearkes** [comment]
Hehe, yes, that is a little cheap. :)

I'm assuming what happened is that you changed from the Complex ($12 a month) to Basic ($5 a month) at the start of the month. So, for example, if you paid us $12 on August 1st, then switched to the Basic plan on August 5th, you would have overpaid by some amount – as most of the month was spent on the Basic plan.

We just roll that account credit over. I should probably fix up the email to show this:

`Paid via credit, $1 balance remains`

(or something like that).

Make sense?

**Comment by d0ugal** [comment]
Yup, that sounds correct. Thanks - just thought I'd report it anyway.

**Comment by pearkes** [comment]
@d0ugal Totally, that's a little weird to see. Thank you! :)
